"""
Central configuration for the Pakistan Rent-a-Car data generator.
Mirrors real operators: RentKA, Haxn Rent a Car, Cars Rental 247, Hassan Rent a Car.
"""

import random
from datetime import date

# ── Simulation window ────────────────────────────────────────────────
SIM_START   = date(2022, 1, 1)
SIM_END     = date(2026, 6, 30)
RANDOM_SEED = 42

# ── Company / fleet size ─────────────────────────────────────────────
NUM_FLEETS   = 4          # distinct rental companies
NUM_VEHICLES = 120        # total cars across all fleets
NUM_DRIVERS  = 60
NUM_STAFF    = 30         # non-driver staff (managers, dispatchers, mechanics)
NUM_CUSTOMERS = 2_000
NUM_TRIPS     = 18_000    # rental / travel records
NUM_MAINTENANCE_RECORDS = 800

# ── PKR exchange rates (approximate mid-2024) ─────────────────────────
USD_TO_PKR = 278.0

# ── Fleet companies (inspired by real operators) ─────────────────────
FLEET_COMPANIES = [
    {
        "name": "Hassan Rent a Car",
        "city": "Gujrat",
        "website": "hassanrentacargujrat.com.pk",
        "secp_registered": True,
        "ntn_registered": True,
        "established_year": 2010,
        "focus": "economy_and_luxury",
    },
    {
        "name": "RentKA",
        "city": "Islamabad",
        "website": "rentka.co",
        "secp_registered": True,
        "ntn_registered": True,
        "established_year": 2018,
        "focus": "chauffeur_driven",
    },
    {
        "name": "Haxn Rent a Car",
        "city": "Islamabad",
        "website": "haxnrentacar.com",
        "secp_registered": False,
        "ntn_registered": True,
        "established_year": 2015,
        "focus": "corporate_and_wedding",
    },
    {
        "name": "Cars Rental 247",
        "city": "Islamabad",
        "website": "carsrental247.com",
        "secp_registered": True,
        "ntn_registered": True,
        "established_year": 2019,
        "focus": "self_drive",
    },
]

# ── Vehicle type catalogue (with realistic PKR daily rates) ──────────
# Sources: haxnrentacar.com, carsrental247.com, rentka.co, carrentpk.com
VEHICLE_TYPES = [
    # category, sub_type, make, model_variants, year_range,
    # seats, fuel_type, transmission,
    # daily_rate_pkr_min, daily_rate_pkr_max,
    # hourly_rate_pkr, km_rate_pkr (for outstation),
    # fuel_efficiency_kmpl_min, fuel_efficiency_kmpl_max
    {
        "category": "Economy",
        "sub_type": "Mini",
        "make": "Suzuki",
        "models": ["Alto VXR", "Alto VXL", "Alto AGS"],
        "year_range": (2018, 2025),
        "seats": 5,
        "fuel_type": "Petrol",
        "transmission": "Manual",
        "daily_rate_min": 3500,
        "daily_rate_max": 5000,
        "hourly_rate": 400,
        "km_rate": 12,
        "fuel_eff_min": 16,
        "fuel_eff_max": 22,
        "deposit_pkr": 10000,
    },
    {
        "category": "Economy",
        "sub_type": "Hatchback",
        "make": "Suzuki",
        "models": ["Wagon R VXR", "Wagon R VXL", "Cultus VXR", "Cultus VXL"],
        "year_range": (2017, 2025),
        "seats": 5,
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "daily_rate_min": 4500,
        "daily_rate_max": 6000,
        "hourly_rate": 500,
        "km_rate": 14,
        "fuel_eff_min": 14,
        "fuel_eff_max": 18,
        "deposit_pkr": 15000,
    },
    {
        "category": "Economy",
        "sub_type": "Sedan",
        "make": "Toyota",
        "models": ["Corolla GLI 1.3", "Corolla XLI", "Corolla Altis 1.6", "Corolla Altis Grande"],
        "year_range": (2018, 2025),
        "seats": 5,
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "daily_rate_min": 5000,
        "daily_rate_max": 9000,
        "hourly_rate": 700,
        "km_rate": 18,
        "fuel_eff_min": 12,
        "fuel_eff_max": 16,
        "deposit_pkr": 20000,
    },
    {
        "category": "Economy",
        "sub_type": "Sedan",
        "make": "Honda",
        "models": ["City 1.2 MT", "City 1.5 AT", "City Aspire"],
        "year_range": (2018, 2025),
        "seats": 5,
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "daily_rate_min": 6000,
        "daily_rate_max": 8000,
        "hourly_rate": 650,
        "km_rate": 17,
        "fuel_eff_min": 12,
        "fuel_eff_max": 15,
        "deposit_pkr": 20000,
    },
    {
        "category": "Executive",
        "sub_type": "Sedan",
        "make": "Honda",
        "models": ["Civic RS 1.5T", "Civic Oriel", "Civic VTi"],
        "year_range": (2020, 2025),
        "seats": 5,
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "daily_rate_min": 9000,
        "daily_rate_max": 12000,
        "hourly_rate": 1000,
        "km_rate": 22,
        "fuel_eff_min": 11,
        "fuel_eff_max": 14,
        "deposit_pkr": 30000,
    },
    {
        "category": "Executive",
        "sub_type": "Crossover",
        "make": "Honda",
        "models": ["BR-V S", "BR-V i-VTEC"],
        "year_range": (2021, 2025),
        "seats": 7,
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "daily_rate_min": 6000,
        "daily_rate_max": 8500,
        "hourly_rate": 800,
        "km_rate": 20,
        "fuel_eff_min": 12,
        "fuel_eff_max": 15,
        "deposit_pkr": 25000,
    },
    {
        "category": "Executive",
        "sub_type": "SUV",
        "make": "Hyundai",
        "models": ["Tucson 2.0 FWD", "Tucson 1.6T AWD"],
        "year_range": (2020, 2025),
        "seats": 5,
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "daily_rate_min": 12000,
        "daily_rate_max": 15000,
        "hourly_rate": 1200,
        "km_rate": 28,
        "fuel_eff_min": 10,
        "fuel_eff_max": 13,
        "deposit_pkr": 40000,
    },
    {
        "category": "Executive",
        "sub_type": "SUV",
        "make": "MG",
        "models": ["HS 1.5T", "HS Essence", "ZS EV"],
        "year_range": (2020, 2025),
        "seats": 5,
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "daily_rate_min": 12000,
        "daily_rate_max": 16000,
        "hourly_rate": 1200,
        "km_rate": 28,
        "fuel_eff_min": 10,
        "fuel_eff_max": 13,
        "deposit_pkr": 40000,
    },
    {
        "category": "Premium_4x4",
        "sub_type": "Pickup_4x4",
        "make": "Toyota",
        "models": ["Hilux Revo SR5", "Hilux Revo V", "Hilux Rocco"],
        "year_range": (2018, 2025),
        "seats": 5,
        "fuel_type": "Diesel",
        "transmission": "Automatic",
        "daily_rate_min": 16000,
        "daily_rate_max": 20000,
        "hourly_rate": 1800,
        "km_rate": 35,
        "fuel_eff_min": 9,
        "fuel_eff_max": 13,
        "deposit_pkr": 50000,
    },
    {
        "category": "Premium_4x4",
        "sub_type": "SUV",
        "make": "Toyota",
        "models": ["Fortuner 2.7 VVTi", "Fortuner 2.8 Diesel"],
        "year_range": (2017, 2025),
        "seats": 7,
        "fuel_type": "Diesel",
        "transmission": "Automatic",
        "daily_rate_min": 17000,
        "daily_rate_max": 22000,
        "hourly_rate": 2000,
        "km_rate": 38,
        "fuel_eff_min": 9,
        "fuel_eff_max": 12,
        "deposit_pkr": 55000,
    },
    {
        "category": "Luxury_4x4",
        "sub_type": "SUV",
        "make": "Toyota",
        "models": ["Land Cruiser Prado 2.7", "Land Cruiser Prado 4.0"],
        "year_range": (2018, 2025),
        "seats": 7,
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "daily_rate_min": 22000,
        "daily_rate_max": 28000,
        "hourly_rate": 2500,
        "km_rate": 50,
        "fuel_eff_min": 7,
        "fuel_eff_max": 10,
        "deposit_pkr": 80000,
    },
    {
        "category": "Luxury_4x4",
        "sub_type": "Full-Size_SUV",
        "make": "Toyota",
        "models": ["Land Cruiser V8 200 Series", "Land Cruiser ZX LC300"],
        "year_range": (2018, 2025),
        "seats": 8,
        "fuel_type": "Diesel",
        "transmission": "Automatic",
        "daily_rate_min": 25000,
        "daily_rate_max": 40000,
        "hourly_rate": 3500,
        "km_rate": 70,
        "fuel_eff_min": 6,
        "fuel_eff_max": 9,
        "deposit_pkr": 100000,
    },
    {
        "category": "Luxury_Sedan",
        "sub_type": "Sedan",
        "make": "Audi",
        "models": ["Audi A5 Sportback", "Audi A6 3.0T"],
        "year_range": (2019, 2025),
        "seats": 5,
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "daily_rate_min": 28000,
        "daily_rate_max": 35000,
        "hourly_rate": 3000,
        "km_rate": 60,
        "fuel_eff_min": 8,
        "fuel_eff_max": 11,
        "deposit_pkr": 100000,
    },
    {
        "category": "Luxury_Sedan",
        "sub_type": "Sedan",
        "make": "Mercedes-Benz",
        "models": ["E-Class E200", "E-Class E300", "S-Class S450"],
        "year_range": (2019, 2025),
        "seats": 5,
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "daily_rate_min": 35000,
        "daily_rate_max": 80000,
        "hourly_rate": 5000,
        "km_rate": 80,
        "fuel_eff_min": 8,
        "fuel_eff_max": 10,
        "deposit_pkr": 150000,
    },
    {
        "category": "Ultra_Luxury",
        "sub_type": "SUV",
        "make": "Land Rover",
        "models": ["Range Rover Autobiography", "Range Rover Sport HSE"],
        "year_range": (2020, 2025),
        "seats": 5,
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "daily_rate_min": 100000,
        "daily_rate_max": 175000,
        "hourly_rate": 12000,
        "km_rate": 200,
        "fuel_eff_min": 5,
        "fuel_eff_max": 8,
        "deposit_pkr": 300000,
    },
    {
        "category": "Van_Minibus",
        "sub_type": "MPV",
        "make": "Suzuki",
        "models": ["APV GL", "APV GLX"],
        "year_range": (2017, 2025),
        "seats": 8,
        "fuel_type": "Petrol",
        "transmission": "Manual",
        "daily_rate_min": 5000,
        "daily_rate_max": 7000,
        "hourly_rate": 600,
        "km_rate": 15,
        "fuel_eff_min": 11,
        "fuel_eff_max": 14,
        "deposit_pkr": 20000,
    },
    {
        "category": "Van_Minibus",
        "sub_type": "Grand_Cabin",
        "make": "Toyota",
        "models": ["Hiace Grand Cabin", "Hiace Super GL"],
        "year_range": (2018, 2025),
        "seats": 14,
        "fuel_type": "Diesel",
        "transmission": "Manual",
        "daily_rate_min": 10000,
        "daily_rate_max": 16000,
        "hourly_rate": 1100,
        "km_rate": 25,
        "fuel_eff_min": 9,
        "fuel_eff_max": 12,
        "deposit_pkr": 40000,
    },
    {
        "category": "Van_Minibus",
        "sub_type": "Coaster",
        "make": "Toyota",
        "models": ["Coaster HZB50 30-Seater", "Coaster HZB50 22-Seater"],
        "year_range": (2015, 2025),
        "seats": 30,
        "fuel_type": "Diesel",
        "transmission": "Manual",
        "daily_rate_min": 15000,
        "daily_rate_max": 20000,
        "hourly_rate": 1800,
        "km_rate": 35,
        "fuel_eff_min": 7,
        "fuel_eff_max": 10,
        "deposit_pkr": 50000,
    },
]

# ── Pakistani cities with lat/lon and demand weight ──────────────────
CITIES = [
    {"name": "Islamabad",  "province": "ICT",   "lat": 33.6844, "lon": 73.0479, "demand": 0.25},
    {"name": "Rawalpindi", "province": "Punjab", "lat": 33.5651, "lon": 73.0169, "demand": 0.12},
    {"name": "Lahore",     "province": "Punjab", "lat": 31.5204, "lon": 74.3587, "demand": 0.20},
    {"name": "Karachi",    "province": "Sindh",  "lat": 24.8607, "lon": 67.0011, "demand": 0.18},
    {"name": "Peshawar",   "province": "KPK",    "lat": 34.0151, "lon": 71.5249, "demand": 0.06},
    {"name": "Murree",     "province": "Punjab", "lat": 33.9078, "lon": 73.3906, "demand": 0.04},
    {"name": "Nathiagali", "province": "KPK",    "lat": 34.0630, "lon": 73.3682, "demand": 0.02},
    {"name": "Abbottabad", "province": "KPK",    "lat": 34.1463, "lon": 73.2117, "demand": 0.03},
    {"name": "Multan",     "province": "Punjab", "lat": 30.1575, "lon": 71.5249, "demand": 0.04},
    {"name": "Faisalabad", "province": "Punjab", "lat": 31.4504, "lon": 73.1350, "demand": 0.03},
    {"name": "Gujranwala", "province": "Punjab", "lat": 32.1877, "lon": 74.1945, "demand": 0.02},
    {"name": "Quetta",     "province": "Balochistan","lat": 30.1798,"lon": 66.9750,"demand": 0.01},
]

# ── Popular intercity routes with typical km and base PKR ─────────────
INTERCITY_ROUTES = [
    {"from": "Islamabad",  "to": "Lahore",      "km": 380, "base_pkr": 8000},
    {"from": "Islamabad",  "to": "Murree",      "km": 70,  "base_pkr": 3500},
    {"from": "Islamabad",  "to": "Nathiagali",  "km": 75,  "base_pkr": 3800},
    {"from": "Islamabad",  "to": "Abbottabad",  "km": 120, "base_pkr": 4500},
    {"from": "Islamabad",  "to": "Peshawar",    "km": 170, "base_pkr": 5000},
    {"from": "Islamabad",  "to": "Karachi",     "km": 1420,"base_pkr": 30000},
    {"from": "Lahore",     "to": "Faisalabad",  "km": 130, "base_pkr": 3500},
    {"from": "Lahore",     "to": "Multan",      "km": 330, "base_pkr": 7000},
    {"from": "Lahore",     "to": "Gujranwala",  "km": 70,  "base_pkr": 2500},
    {"from": "Karachi",    "to": "Lahore",      "km": 1230,"base_pkr": 28000},
    {"from": "Rawalpindi", "to": "Islamabad",   "km": 15,  "base_pkr": 1500},
]

# ── Trip/booking types ────────────────────────────────────────────────
BOOKING_TYPES = [
    "City Ride",
    "Airport Transfer",
    "Intercity",
    "Wedding",
    "Corporate",
    "Tourism / Northern Areas",
    "Monthly Contract",
    "Event",
]

# ── Maintenance categories ────────────────────────────────────────────
MAINTENANCE_TYPES = [
    {"type": "Oil Change",          "avg_cost": 3500,  "interval_km": 5000},
    {"type": "Tyre Rotation",       "avg_cost": 1000,  "interval_km": 10000},
    {"type": "Tyre Replacement",    "avg_cost": 18000, "interval_km": 40000},
    {"type": "Brake Pad Replace",   "avg_cost": 8000,  "interval_km": 25000},
    {"type": "AC Service",          "avg_cost": 4500,  "interval_km": 15000},
    {"type": "Battery Replace",     "avg_cost": 12000, "interval_km": 50000},
    {"type": "Transmission Service","avg_cost": 9000,  "interval_km": 30000},
    {"type": "Engine Tune-Up",      "avg_cost": 6000,  "interval_km": 20000},
    {"type": "Suspension Repair",   "avg_cost": 15000, "interval_km": 60000},
    {"type": "Body Repair / Dent",  "avg_cost": 25000, "interval_km": None},
    {"type": "Glass Replace",       "avg_cost": 20000, "interval_km": None},
    {"type": "Accident Repair",     "avg_cost": 80000, "interval_km": None},
    {"type": "Periodic Inspection", "avg_cost": 2000,  "interval_km": 5000},
]

# ── Fuel prices (PKR/litre, approximate historical) ───────────────────
FUEL_PRICES_TIMELINE = [
    # (date_str, petrol_pkr, diesel_pkr, cng_pkr)
    ("2022-01-01", 144.82, 127.30, 115.00),
    ("2022-06-01", 179.86, 174.15, 135.00),
    ("2022-10-01", 224.80, 235.30, 160.00),
    ("2023-02-01", 249.80, 263.00, 175.00),
    ("2023-07-01", 290.45, 283.00, 190.00),
    ("2024-01-01", 279.75, 284.00, 195.00),
    ("2024-07-01", 268.42, 271.34, 185.00),
    ("2025-01-01", 255.63, 259.90, 180.00),
    ("2025-07-01", 249.50, 253.00, 175.00),
    ("2026-01-01", 243.80, 247.00, 170.00),
]

# ── Driver telematics / behaviour buckets ─────────────────────────────
DRIVER_BEHAVIOR_PROFILES = {
    "excellent":  {"harsh_brake_rate": 0.02, "harsh_accel_rate": 0.02, "idle_pct": 0.05, "speeding_pct": 0.03},
    "good":       {"harsh_brake_rate": 0.05, "harsh_accel_rate": 0.05, "idle_pct": 0.10, "speeding_pct": 0.07},
    "average":    {"harsh_brake_rate": 0.10, "harsh_accel_rate": 0.10, "idle_pct": 0.18, "speeding_pct": 0.15},
    "poor":       {"harsh_brake_rate": 0.20, "harsh_accel_rate": 0.18, "idle_pct": 0.28, "speeding_pct": 0.25},
    "dangerous":  {"harsh_brake_rate": 0.35, "harsh_accel_rate": 0.30, "idle_pct": 0.35, "speeding_pct": 0.40},
}

# ── Staff roles ────────────────────────────────────────────────────────
STAFF_ROLES = [
    "Fleet Manager", "Operations Manager", "Booking Coordinator",
    "Accountant", "Dispatcher", "Mechanic", "Cleaner / Detailer",
    "Customer Service Rep", "HR Manager", "IT / Data Analyst",
]

# ── Payment methods ────────────────────────────────────────────────────
PAYMENT_METHODS = ["Cash", "JazzCash", "EasyPaisa", "Bank Transfer", "Card (POS)"]

# ── Billing surcharge types ───────────────────────────────────────────
SURCHARGE_TYPES = [
    "Airport Pickup/Drop",
    "Night Surcharge",
    "Extra KM",
    "Extra Hours",
    "Fuel Surcharge",
    "Toll Charges",
    "Waiting Charges",
    "Outstation Surcharge",
    "Peak Season Premium",
    "Security Deposit",
]
